// src/components/Button/button.tsx
/*
 * @Author: 徐家俊 15151832830@163.com
 * @Date: 2024-11-11 12:13:29
 * @LastEditTime: 2024-11-11 12:13:31
 * @LastEditors: 徐家俊 15151832830@163.com
 * @Description:
 * @FilePath: /xujiajun.github.io/src/components/Button/index.tsx
 */

import React from 'react'

interface MyComponentProps {
  title: string
}

const MyComponent: React.FC<MyComponentProps> = ({ title }) => {
  return (
    <div>
      <h2>{title}</h2>
      <p>This is a simple component.</p>
    </div>
  )
}

export default MyComponent

// src/components/Button/button.vue
<!--
 * @Author: 徐家俊 15151832830@163.com
 * @Date: 2024-10-29 14:49:07
 * @LastEditTime: 2024-10-29 14:49:09
 * @LastEditors: 徐家俊 15151832830@163.com
 * @Description: 
 * @FilePath: /my-astro/src/components/Button/button.vue
-->

<template>
  <div class="-view">
    <NButton>asdasda></NButton>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { NButton } from 'naive-ui'
</script>
