// src/components/Button/button.tsx
/*
 * @Author: 徐家俊 15151832830@163.com
 * @Date: 2024-11-11 12:13:29
 * @LastEditTime: 2024-11-11 12:13:31
 * @LastEditors: 徐家俊 15151832830@163.com
 * @Description:
 * @FilePath: /xujiajun.github.io/src/components/Button/index.tsx
 */

import React from 'react'

interface MyComponentProps {
  title: string
}

const MyComponent: React.FC<MyComponentProps> = ({ title }) => {
  return (
    <div>
      <h2>{title}</h2>
      <p>This is a simple component.</p>
    </div>
  )
}

export default MyComponent

// packages/components/button/src/button.vue
<!--
 * @Author: 徐家俊 15151832830@163.com
 * @Date: 2024-12-10 17:29:44
 * @LastEditTime: 2024-12-10 17:36:24
 * @LastEditors: 徐家俊 15151832830@163.com
 * @Description: 
 * @FilePath: /xujiajun.github.io/packages/components/src/components/Button/button.vue
-->
<script setup lang='ts'>
defineOptions({
  name: 'BdButton'
})
import {ElButton } from 'element-plus'
</script>

<template>
  <el-button type="primary">test</el-button>
</template>

<style lang='scss' scoped>

</style>
